source 'https://rubygems.org'

gem 'octokit', '~> 4.0'
gem 'netrc', '~> 0.11.0'
gem 'clamp'
gem 'redis', '~>3.2'
gem 'reactive-ruby'
gem 'opal'
gem 'browser'
gem 'opal-browser'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'sinatra_auth_github'
gem 'haml'
gem 'sass'
