source 'https://rubygems.org'

gem 'octokit', '~> 4.0'
gem 'netrc', '~> 0.11.0'
gem 'clamp'
gem 'redis', '~>3.2'
gem 'sinatra'
gem 'thin'
gem 'sinatra-contrib'
gem 'sinatra_auth_github'
gem 'activesupport', '~> 4.2', '>= 4.2.6'
gem 'sidekiq'
gem 'sidekiq-superworker'
gem 'byebug'
