---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: github-tools-app-server
  labels:
    project: github-tools
    role: app-server
spec:
  replicas: 1
  selector:
    matchLabels:
      project: github-tools
      role: app-server
  strategy:
    type: RollingUpdate
  template:
    metadata:
      name: github-tools-app-server
      labels:
        project: github-tools
        role: app-server
      annotations:
        secret/WARDEN_GITHUB_VERIFIER_SECRET: 'verifier_secret'
        secret/GITHUB_CLIENT_SECRET: 'client_secret'
        secret/GITHUB_CLIENT_ID: 'client_id'
    spec:
      containers:
      - name: github-tools
        image: docker-registry.zende.sk/samson_non_prod/github-thirdparty-restriction:latest
        command:
          - "npm"
          - "run"
          - "web-server"
        resources:
          limits:
            cpu: 20m
            memory: 512Mi
        ports:
        - name: main-port
          containerPort: 9393
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /z/ping
            port: 9393
          initialDelaySeconds: 5
          timeoutSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  name: github-tools
  labels:
    project: github-tools
    role: app-server
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: main-port
  selector:
    project: github-tools
    role: app-server
