---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: github-tools-redis
  labels:
    project: github-tools
    role: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      project: github-tools
      role: redis
  strategy:
    type: RollingUpdate
  template:
    metadata:
      name: github-tools-redis
      labels:
        project: github-tools
        role: redis
    spec:
      containers:
      - name: redis
        image: redis:2.8
        command:
          - "redis-server"
          - "--appendonly yes"
        ports:
        - name: redis-server
          containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: github-tools-redis
  labels:
    project: github-tools
    role: redis
spec:
  type: NodePort
  ports:
  - port: 6379
    targetPort: redis-server
  selector:
    project: github-tools
    role: redis
